-- OneShot M6: style presets (image) and camera-move presets (video).
-- {prompt} is replaced with the user's prompt; the template adds the craft.

insert into public.presets (kind, slug, name, description, thumbnail_path, prompt_template, sort) values
  ('image', 'cinematic', 'Cinematic', 'Film still, dramatic light',
   '/presets/cinematic.jpg',
   '{prompt}. Cinematic film still, anamorphic lens, dramatic volumetric lighting, shallow depth of field, rich colour grade, 35mm film grain.', 10),
  ('image', 'anime', 'Anime', 'Hand-drawn anime look',
   '/presets/anime.jpg',
   '{prompt}. Anime illustration in the style of a hand-drawn Japanese animated film, clean line art, soft cel shading, painterly background, vibrant colours.', 20),
  ('image', 'product', 'Product shot', 'Clean studio packshot',
   '/presets/product.jpg',
   '{prompt}. Professional studio product photograph, seamless backdrop, softbox key light with subtle rim light, crisp reflections, ultra sharp, commercial advertising quality.', 30),
  ('image', 'film-noir', 'Film noir', 'Moody black and white',
   '/presets/film-noir.jpg',
   '{prompt}. Film noir, black and white photograph, hard low-key lighting, deep shadows, venetian blind light patterns, 1940s mood, high contrast.', 40),
  ('image', 'watercolor', 'Watercolour', 'Soft painted washes',
   '/presets/watercolor.jpg',
   '{prompt}. Delicate watercolour painting on textured paper, soft bleeding washes, loose brushwork, light pastel palette, white paper showing through.', 50),
  ('image', '3d-render', '3D render', 'Glossy stylised 3D',
   '/presets/3d-render.jpg',
   '{prompt}. Stylised 3D render, soft global illumination, smooth rounded shapes, glossy materials, playful colours, octane-style studio lighting.', 60),
  ('image', 'editorial', 'Editorial portrait', 'Magazine-cover portrait',
   '/presets/editorial.jpg',
   '{prompt}. High-fashion editorial portrait photograph, magazine cover quality, beauty dish lighting, natural skin texture, 85mm lens, elegant composition.', 70),
  ('image', 'cyberpunk', 'Neon cyberpunk', 'Rain, neon and chrome',
   '/presets/cyberpunk.jpg',
   '{prompt}. Neon cyberpunk scene at night, rain-slicked streets, magenta and cyan neon reflections, holographic signs, atmospheric haze, blade-runner mood.', 80),

  ('video', 'dolly-in', 'Dolly in', 'Slow push towards the subject',
   '/presets/camera-sample.jpg',
   '{prompt}. Camera: slow, smooth dolly-in pushing steadily towards the subject, stabilised, cinematic.', 10),
  ('video', 'orbit', 'Orbit', 'Circle around the subject',
   '/presets/camera-sample.jpg',
   '{prompt}. Camera: smooth 180-degree orbit around the subject at eye level, subject stays centred, parallax in the background.', 20),
  ('video', 'crane-up', 'Crane up', 'Rise up to reveal the scene',
   '/presets/camera-sample.jpg',
   '{prompt}. Camera: crane shot rising slowly upward and tilting down, revealing the wider scene below.', 30),
  ('video', 'fpv', 'FPV drone', 'Fast, swooping flight',
   '/presets/camera-sample.jpg',
   '{prompt}. Camera: fast FPV drone flight, swooping low and banking through the scene with dynamic motion.', 40),
  ('video', 'handheld', 'Handheld', 'Documentary feel',
   '/presets/camera-sample.jpg',
   '{prompt}. Camera: handheld documentary style, subtle natural shake, following the action closely.', 50),
  ('video', 'tracking', 'Tracking', 'Follow alongside the subject',
   '/presets/camera-sample.jpg',
   '{prompt}. Camera: lateral tracking shot moving alongside the subject at the same speed, smooth gimbal motion.', 60),
  ('video', 'pan', 'Slow pan', 'Sweep across the scene',
   '/presets/camera-sample.jpg',
   '{prompt}. Camera: slow horizontal pan from left to right across the scene, tripod-steady.', 70),
  ('video', 'pull-out', 'Pull out', 'Reveal by moving back',
   '/presets/camera-sample.jpg',
   '{prompt}. Camera: slow pull-back dolly-out from a close-up to reveal the full environment.', 80);
